FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:focal

# set dbus address
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ENV UDEV=1
ENV BALENA_DEVICE_TYPE=%%BALENA_MACHINE_NAME%%

# copy base scripts to the created folder
COPY install.sh /root/install.sh
COPY run.sh /root/run.sh

# add specific apps related conf and script
COPY snapserver.conf /etc/snapserver.conf

# run script to prepare env
RUN /bin/bash /root/install.sh

CMD [ "/bin/bash", "/root/run.sh" ]