version: '2'

volumes:
  cache-snapcast:
  cache-spotify:

services:
  mopidy:
    build: ./mopidy
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  snapcast:
    build: ./snapcast
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  spotify:
    build: ./spotify
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
      - cache-spotify:/var/cache/spotify
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  bluetooth:
    build: ./bluetooth
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  bonjour:
    build: ./bonjour
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  manager:
    build: ./manager
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  traefik:
    build: ./traefik
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'