version: '2'

volumes:
  cache-snapcast:
  cache-spotify:

services:
  snapserver:
    build: ./alpine/snapserver
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  snapwatcher:
    build: ./alpine/snapwatcher
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  snapclient:
    build: ./alpine/snapclient
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  spotify:
    build: ./alpine/spotify
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - cache-snapcast:/var/cache/snapcast
      - cache-spotify:/var/cache/spotify
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'

  # traefik:
  #   build: ./traefik
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.balena-socket: '1'
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.sysfs: '1'
  #     io.balena.features.procfs: '1'
  #     io.balena.features.journal-logs: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'
  #     io.balena.update.strategy: download-then-kill
  #     io.balena.update.handover-timeout: ''
  # mopidy:
  #   build: ./mopidy
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - cache-snapcast:/var/cache/snapcast
  #   labels:
  #     io.balena.features.balena-socket: '1'
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.sysfs: '1'
  #     io.balena.features.procfs: '1'
  #     io.balena.features.journal-logs: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'
  #     io.balena.update.strategy: download-then-kill
  #     io.balena.update.handover-timeout: ''
  # snapcast:
  #   build: ./snapcast
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - cache-snapcast:/var/cache/snapcast
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'
  # bluetooth:
  #   build: ./bluetooth
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - cache-snapcast:/var/cache/snapcast
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'
  # bonjour:
  #   build: ./bonjour
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'
  # manager:
  #   build: ./manager
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.balena-api: '1'