FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.13

# set dbus address
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ENV UDEV=1
ENV BALENA_DEVICE_TYPE=%%BALENA_MACHINE_NAME%%

# copy base scripts to the created folder
COPY install.sh /root/install.sh
COPY run.sh /root/run.sh
COPY snapwatcher.sh /root/snapwatcher.sh

# run script to prepare env
RUN /bin/ash /root/install.sh

# run programm
CMD [ "/bin/ash", "/root/run.sh" ]